import "./globals.css";
// forma de importar Fonts en Next
import {Josefin_Sans} from 'next/font/google';

export const metadata = {
  title: "Optimum Stucco INC",
  description: "Generated by create next app",
};

//Uso de la Font + meterla en el body como una class
const Josef = Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      {/* Links para el SlickSlider carrousel */}
      <head>
        <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </head>
      
      <body className={Josef.className}>

        {/* <Navbar /> */} {/* PARA TODAS LAS PÁGINAS. */}
        
        {children}

        {/* <Footer /> */}
        
        
        </body>
    </html>
  );
}
